### ISSUE TITLE
Examples with auth/cookies?

### ISSUE THREAD

**Issue by rothgar** [davesheldon/nap#15]
Maybe this isn't the intended use case for `nap` so I wanted to ask before I tried it.

I'd like to do some simple web scraping for data on a page that requires authentication. I have a list of URLs and data to grab and I know I could do it with playwright or directly in lots of other languages and frameworks but I like the simplicity of naps config language.

For example, [this page](https://www.linkedin.com/posts/justingarrison_kubernetes-aws-eks-activity-6970427108980383744-2iwb) on linkedIn has an [analytics page](https://www.linkedin.com/analytics/post-summary/urn:li:activity:6970427108980383744/) that only my user has authentication to view and I would like to pass my authentication cookies to get the data.

I want to export the data into a file as part of a script but I wanted to ask for examples on how this is intended to be done and if this is a good use case for `nap` or if I should use something else.

Thanks

**Comment by davesheldon** [comment]
Hey Justin, thanks for checking out Nap!

I do think I will add cookie support at some point soon. We have to add
that to enable certain test flows. I haven't explored it yet. If you want
to put together a PR I can review it, or else you can wait until I get
around to it.

I'm not sure that scraping fits into our goals, exactly, but you could sort
of get there by adding "verbose: true" to your request YAML. That's an
undocumented property that basically just dumps the raw request and
response to stdout (I use it a lot for debugging/testing during
development). At that point it's a matter of trimming and pushing the
output into a file. If you run with the -q flag it'll trim out some of the
output for you.

**Comment by rothgar** [comment]
Thanks for the quick response. That's good to know it's not a feature you have and I'm ok doing it with something else. I wanted to check if I missed something in the docs and if it was an intended use case.

Feel free to close this issue if you don't want to keep it around while you work on cookie support.
